// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatRoom_JoinChat_FullMethodName    = "/chitChat.ChatRoom/JoinChat"
	ChatRoom_LeaveChat_FullMethodName   = "/chitChat.ChatRoom/LeaveChat"
	ChatRoom_SendMessage_FullMethodName = "/chitChat.ChatRoom/SendMessage"
)

// ChatRoomClient is the client API for ChatRoom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatRoomClient interface {
	JoinChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (ChatRoom_JoinChatClient, error)
	LeaveChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Ack, error)
	SendMessage(ctx context.Context, in *Chat, opts ...grpc.CallOption) (*Ack, error)
}

type chatRoomClient struct {
	cc grpc.ClientConnInterface
}

func NewChatRoomClient(cc grpc.ClientConnInterface) ChatRoomClient {
	return &chatRoomClient{cc}
}

func (c *chatRoomClient) JoinChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (ChatRoom_JoinChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatRoom_ServiceDesc.Streams[0], ChatRoom_JoinChat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatRoomJoinChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatRoom_JoinChatClient interface {
	Recv() (*Chat, error)
	grpc.ClientStream
}

type chatRoomJoinChatClient struct {
	grpc.ClientStream
}

func (x *chatRoomJoinChatClient) Recv() (*Chat, error) {
	m := new(Chat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatRoomClient) LeaveChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, ChatRoom_LeaveChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomClient) SendMessage(ctx context.Context, in *Chat, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, ChatRoom_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatRoomServer is the server API for ChatRoom service.
// All implementations must embed UnimplementedChatRoomServer
// for forward compatibility
type ChatRoomServer interface {
	JoinChat(*Client, ChatRoom_JoinChatServer) error
	LeaveChat(context.Context, *Client) (*Ack, error)
	SendMessage(context.Context, *Chat) (*Ack, error)
	mustEmbedUnimplementedChatRoomServer()
}

// UnimplementedChatRoomServer must be embedded to have forward compatible implementations.
type UnimplementedChatRoomServer struct {
}

func (UnimplementedChatRoomServer) JoinChat(*Client, ChatRoom_JoinChatServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinChat not implemented")
}
func (UnimplementedChatRoomServer) LeaveChat(context.Context, *Client) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveChat not implemented")
}
func (UnimplementedChatRoomServer) SendMessage(context.Context, *Chat) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatRoomServer) mustEmbedUnimplementedChatRoomServer() {}

// UnsafeChatRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatRoomServer will
// result in compilation errors.
type UnsafeChatRoomServer interface {
	mustEmbedUnimplementedChatRoomServer()
}

func RegisterChatRoomServer(s grpc.ServiceRegistrar, srv ChatRoomServer) {
	s.RegisterService(&ChatRoom_ServiceDesc, srv)
}

func _ChatRoom_JoinChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Client)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatRoomServer).JoinChat(m, &chatRoomJoinChatServer{stream})
}

type ChatRoom_JoinChatServer interface {
	Send(*Chat) error
	grpc.ServerStream
}

type chatRoomJoinChatServer struct {
	grpc.ServerStream
}

func (x *chatRoomJoinChatServer) Send(m *Chat) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatRoom_LeaveChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).LeaveChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatRoom_LeaveChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).LeaveChat(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRoom_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatRoom_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).SendMessage(ctx, req.(*Chat))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatRoom_ServiceDesc is the grpc.ServiceDesc for ChatRoom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatRoom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chitChat.ChatRoom",
	HandlerType: (*ChatRoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeaveChat",
			Handler:    _ChatRoom_LeaveChat_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatRoom_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinChat",
			Handler:       _ChatRoom_JoinChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/proto.proto",
}
